
discordConfig:
  prefix: $
  deafaultChannel: --channel Id--

#
# Database types:
#
#   remote database:
#     - MySQL
#     - MongoDB
#
#   local database:
#     -json
#

database: json


# If MySQL is chosen database:
sqlConfig:
  databaseName: --database name--

  
