
discordConfig:
  prefix: $
  deafaultChannel: --channel Id--

#
# Database types:
#
#   remote database:
#     - MySQL !!MySQL has not been tested yet but might work!!
#     - MongoDB !!!MongoDB is a upcomming feature!!!
#
#   local database:
#     -json
#

database: json


# If MySQL is chosen database:
sqlConfig:
  databaseName: --database name--

  
