name: discordPaperPlugin
version: 0.0.1
api-version: 1.16
main: co.za.bonk.DiscordPaperPlugin

commands:
  discord:
    description: this plugin's general command
    usage: /<command> [register]
    permission: discord.default